// <auto-generated />
using Faoem.Facility.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faoem.Facility.Migrations.Sqlite
{
    [DbContext(typeof(SqliteFacilityDbContext))]
    partial class SqliteFacilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Faoem.Facility.Models.Facility", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LowerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("lower_name");

                    b.Property<string>("LowerSerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("lower_serial_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.ToTable("facility_facility", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
