export const settingLang = {
  en: {
    el: {
      setting: {
        facilitySetting: 'Facility Setting',
        save: 'Save',
        index: 'Index',
        name: 'Name',
        isEnabled: 'Is Enabled',
        description: 'Description',
        serialNumber: 'Serial Number',
        yes: 'Yes',
        no: 'No',
        addFacility: 'Add Facility',
        requiredMsg: 'Required',
        add: 'Add',
        addSuccessful: 'Add Facility Successful',
        addFailed: 'Add Facility Failed',
        update: 'Update',
        updateFacility: 'Update Facility',
        updateSuccessful: 'Update Facility Successful',
        updateFailed: 'Update Facility Failed',
        delete: 'Delete',
        deleteFacility: 'Delete Facility',
        deleteSuccessful: 'Delete Facility Successful',
        deleteFailed: 'Delete Facility Failed',
        deleteConfirm:
          'This action cannot be undone. Are you sure you want to delete the facility?',
      },
    },
  },
  zhCn: {
    el: {
      setting: {
        facilitySetting: '设备设置',
        save: '保存',
        index: '序号',
        name: '名称',
        isEnabled: '是否启用',
        description: '描述',
        serialNumber: '设备编号',
        yes: '是',
        no: '否',
        addFacility: '添加设备',
        requiredMsg: '必填',
        add: '添加',
        addSuccessful: '添加设备成功',
        addFailed: '添加设备失败',
        update: '更新',
        updateFacility: '更新设备',
        updateSuccessful: '更新设备成功',
        updateFailed: '更新设备失败',
        delete: '删除',
        deleteFacility: '删除设备',
        deleteSuccessful: '删除设备成功',
        deleteFailed: '删除设备失败',
        deleteConfirm: '删除后无法恢复，确定要删除设备吗？',
      },
    },
  },
}
