// <auto-generated />
using Faoem.FacilityStatus.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faoem.FacilityStatus.Migrations.Sqlite
{
    [DbContext(typeof(SqliteFacilityStatusDbContext))]
    partial class SqliteFacilityStatusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Faoem.FacilityStatus.Models.StatusBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BindingType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("binding_type");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_name");

                    b.Property<string>("ConnectorInstance")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connector_instance");

                    b.Property<string>("DataPoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_point");

                    b.Property<long>("FacilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("facility_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("facility_status_facility_status_binding", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
