// <auto-generated />
using Faoem.Shift.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faoem.Shift.Migrations.Sqlite
{
    [DbContext(typeof(SqliteShiftDbContext))]
    [Migration("20240816132912_000000")]
    partial class _000000
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Faoem.Shift.Models.Shift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasComment("班次 Id");

                    b.Property<long>("EndTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_time")
                        .HasComment("结束时间，unix 时间戳");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled")
                        .HasComment("是否启用");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("班次名称");

                    b.Property<byte>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number")
                        .HasComment("班次编号");

                    b.Property<bool>("SpanTheDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("span_the_day")
                        .HasComment("是否跨天");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_time")
                        .HasComment("开始时间，unix 时间戳");

                    b.HasKey("Id");

                    b.ToTable("shift_shift", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
