export const maintainPlanLang = {
  en: {
    el: {
      maintainPlan: {
        addMaintainPlan: 'Add Maintain Plan',
        maintainCycleWithUnit: 'Maintain Cycle(days)',
        add: 'Add',
        addSuccess: 'The maintain plan has been added.',
        addFailed: 'Failed to add the maintain plan.',
        maintainPlan: 'Maintain Plan',
        createdAt: 'Create At',
        lastMaintainAt: 'Last Maintain At',
        nextMaintainAt: 'Next Maintain At',
        status: 'Status',
        planing: 'Planing',
        remind: 'Remind',
        expired: 'Expired',
        overdue: 'Overdue',
        delete: 'Delete',
        deleteConfirm: 'Are you sure to delete?',
        deleteSuccess: 'The maintain plan has been deleted.',
        deleteFailed: 'Failed to delete the maintain plan.',
      },
    },
  },
  zhCn: {
    el: {
      maintainPlan: {
        addMaintainPlan: '添加维护计划',
        maintainCycleWithUnit: '维护周期（天）',
        add: '添加',
        addSuccess: '维护计划添加成功',
        addFailed: '维护计划添加失败',
        maintainPlan: '维护计划',
        createdAt: '创建时间',
        lastMaintainAt: '上次维护时间',
        nextMaintainAt: '下次维护时间',
        status: '状态',
        planing: '计划中',
        remind: '提醒',
        expired: '到期',
        overdue: '超期',
        delete: '删除',
        deleteConfirm: '确定删除吗？',
        deleteSuccess: '维护计划删除成功',
        deleteFailed: '维护计划删除失败',
      },
    },
  },
}
