export const menuLang = {
  en: {
    el: {
      menu: {
        menuSetting: 'Menu Setting',
        addRootMenu: 'Add Root Menu',
        name: 'Name',
        route: 'Route',
        routeTip:
          '* This setting may cause some features to be unavailable. Please update it with caution.',
        update: 'Update',
        delete: 'Delete',
        addMenu: 'Add Menu',
        isSubMenu: 'Is Sub Menu',
        add: 'Add',
        deleteConfirm:
          'This action cannot be undone. Are you sure you want to delete the menu?',
        deleteTip: 'The submenus will be deleted together.',
        updateMenu: 'Update Menu',
        deleteMenu: 'Delete Menu',
        updateMenuOrder: 'Update Menu Order',
        addSuccessful: 'The menu has been added.',
        addFailed: 'Failed to add the menu.',
        updateSuccessful: 'The menu has been updated.',
        updateFailed: 'Failed to update the menu.',
        deleteSuccessful: 'The menu has been deleted.',
        deleteFailed: 'Failed to delete the menu.',
        updateOrderSuccessful: 'The menu order has been updated.',
        updateOrderFailed: 'Failed to update the menu order.',
      },
    },
  },
  zhCn: {
    el: {
      menu: {
        menuSetting: '菜单设置',
        addRootMenu: '添加根菜单',
        name: '名称',
        route: '路由',
        routeTip: '* 这个设置可能会导致某些功能不可用，请谨慎处理。',
        update: '更新',
        delete: '删除',
        addMenu: '添加菜单',
        isSubMenu: '是否为子菜单',
        add: '添加',
        deleteConfirm: '删除后无法恢复，确定要删除菜单吗？',
        deleteTip: '子菜单将会一并删除。',
        updateMenu: '更新菜单',
        deleteMenu: '删除菜单',
        updateMenuOrder: '更新菜单顺序',
        addSuccessful: '菜单已添加',
        addFailed: '添加菜单失败',
        updateSuccessful: '菜单已更新',
        updateFailed: '更新菜单失败',
        deleteSuccessful: '菜单已删除',
        deleteFailed: '删除菜单失败',
        updateOrderSuccessful: '菜单顺序已更新',
        updateOrderFailed: '更新菜单顺序失败',
      },
    },
  },
}
