export const roleLang = {
  en: {
    el: {
      role: {
        roleSetting: 'Role Setting',
        addRole: 'Add Role',
        roleName: 'Role Name',
        update: 'Update',
        delete: 'Delete',
        roleMenu: 'Role Menu',
        rolePermission: 'Role Permission',
        add: 'Add',
        roleNameRule1: 'Must start with a letter.',
        roleNameRule2: 'Can only contain letters, digits, and underscores.',
        roleNameRule3: 'Must be between 4 and 32 characters.',
        deleteConfirm:
          'This action cannot be undone. Are you sure you want to delete the role?',
        roleColon: 'Role: ',
        controller: 'Controller',
        method: 'Method',
        route: 'Route',
        description: 'Description',
        updateRole: 'Update Role',
        deleteRole: 'Delete Role',
        invalidRoleName: 'Invalid role name.',
        addSuccessful: 'The role has been added.',
        addFailed: 'Failed to add the role.',
        updateSuccessful: 'The role has been updated.',
        updateFailed: 'Failed to update the role.',
        deleteSuccessful: 'The role has been deleted.',
        deleteFailed: 'Failed to delete the role.',
        updateRoleMenuSuccessful: 'The menu has been updated.',
        updateRoleMenuFailed: 'Failed to update the menu.',
        updateRolePermissionSuccessful: 'The permission has been updated.',
        updateRolePermissionFailed: 'Failed to update the permission.',
        select: 'Select',
        selectRole: 'Select Role',
        role: 'Role',
      },
    },
  },
  zhCn: {
    el: {
      role: {
        roleSetting: '角色设置',
        addRole: '添加角色',
        roleName: '角色名称',
        update: '更新',
        delete: '删除',
        roleMenu: '角色菜单',
        rolePermission: '角色权限',
        add: '添加',
        roleNameRule1: '必须以字母开头。',
        roleNameRule2: '只能包含字母、数字和下划线。',
        roleNameRule3: '长度在 4 到 32 个字符之间。',
        deleteConfirm: '删除后无法恢复，确定要删除角色吗?',
        roleColon: '角色：',
        controller: '控制器',
        method: '方法',
        route: '路由',
        description: '描述',
        updateRole: '更新角色',
        deleteRole: '删除角色',
        invalidRoleName: '角色名称格式错误',
        addSuccessful: '角色已添加',
        addFailed: '添加角色失败',
        updateSuccessful: '角色已更新',
        updateFailed: '更新角色失败',
        deleteSuccessful: '角色已删除',
        deleteFailed: '删除角色失败',
        updateRoleMenuSuccessful: '角色菜单已更新',
        updateRoleMenuFailed: '更新角色菜单失败',
        updateRolePermissionSuccessful: '角色权限已更新',
        updateRolePermissionFailed: '更新角色权限失败',
        select: '选择',
        selectRole: '选择角色',
        role: '角色',
      },
    },
  },
}
