export const userLang = {
  en: {
    el: {
      user: {
        profile: 'Profile',
        userProfile: 'User Profile',
        username: 'User Name',
        fullName: 'Full Name',
        updateUserInfo: 'Update User Info',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        passwordTip: 'Must be between 6 and 32 characters.',
        userSetting: 'User Setting',
        addUser: 'Add User',
        lastLogin: 'Last Login',
        delete: 'Delete',
        password: 'Password',
        ok: 'OK',
        updateUserRole: 'Update User Role',
        userColon: 'User: ',
        roleName: 'Role Name',
        deleteConfirm:
          'This action cannot be undone. Are you sure you want to delete the user?',
        usernameRule1: 'Must start with a letter.',
        usernameRule2: 'Can only contain letters, digits, and underscores.',
        usernameRule3: 'Must be between 4 and 32 characters.',
        passwordRule: 'Must be between 6 and 32 characters.',
        keepEmpty: 'Keep empty to remain unchanged',
        updateUser: 'Update User',
        deleteUser: 'Delete User',
        add: 'Add',
        invalidUsername: 'Invalid user name.',
        addSuccessful: 'The user has been added.',
        addFailed: 'Failed to add the user.',
        invalidPassword: 'Invalid password.',
        passwordNotMatch: 'The passwords do not match.',
        updateSuccessful: 'The user has been updated.',
        updateFailed: 'Failed to update the user.',
        update: 'Update',
        updatePassword: 'Update Password',
        updatePasswordSuccessful: 'The password has been updated.',
        updatePasswordFailed: 'Failed to update the password',
        deleteSuccessful: 'The user has been deleted.',
        deleteFailed: 'Failed to delete the user.',
        userRolesUpdateSuccessful: 'The roles has been updated.',
        userRolesUpdateFailed: 'Failed to update the roles.',
        updateUserInfoSuccessful: 'The user information has been updated.',
        updateUserInfoFailed: 'Failed to update the user information.',
        invalidUsernameOrPassword: 'Invalid user name or password.',
        selectUser: 'Select User',
        select: 'Select',
        unselect: 'Unselect',
        user: 'User',
      },
    },
  },
  zhCn: {
    el: {
      user: {
        profile: '个人资料',
        userProfile: '用户信息',
        username: '用户名',
        fullName: '全名',
        updateUserInfo: '更新用户信息',
        currentPassword: '当前密码',
        newPassword: '新密码',
        confirmNewPassword: '确认新密码',
        passwordTip: '长度在 6 到 32 个字符之间。',
        userSetting: '用户设置',
        addUser: '添加用户',
        lastLogin: '上次登录',
        delete: '删除',
        password: '密码',
        ok: '确定',
        updateUserRole: '更新用户角色',
        userColon: '用户：',
        roleName: '角色名',
        deleteConfirm: '删除后无法恢复，确定要删除用户吗？',
        usernameRule1: '必须以字母开头。',
        usernameRule2: '只能包含字母、数字和下划线。',
        usernameRule3: '长度在 4 到 32 个字符之间。',
        passwordRule: '长度在 6 到 32 个字符之间。',
        keepEmpty: '留空时保持不变',
        updateUser: '更新用户',
        deleteUser: '删除用户',
        add: '添加',
        invalidUsername: '用户名格式错误',
        addSuccessful: '添加用户成功',
        addFailed: '添加用户失败',
        invalidPassword: '密码格式错误',
        passwordNotMatch: '两次输入密码不一致',
        updateSuccessful: '用户已更新',
        updateFailed: '更新用户失败',
        update: '更新',
        updatePassword: '修改密码',
        updatePasswordSuccessful: '修改密码成功',
        updatePasswordFailed: '修改密码失败',
        deleteSuccessful: '用户已删除',
        deleteFailed: '删除用户失败',
        userRolesUpdateSuccessful: '用户角色已更新',
        userRolesUpdateFailed: '更新用户角色失败',
        updateUserInfoSuccessful: '更新用户信息成功',
        updateUserInfoFailed: '更新用户信息失败',
        invalidUsernameOrPassword: '用户名或密码无效',
        selectUser: '选择用户',
        select: '选择',
        unselect: '取消选择',
        user: '用户',
      },
    },
  },
}
