// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tsjy.DbContexts;

#nullable disable

namespace Tsjy.Migrations.Sqlite
{
    [DbContext(typeof(SqliteTsjyDbContext))]
    [Migration("20241104085049_0012")]
    partial class _0012
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Tsjy.Models.TsjyAlarmDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_name");

                    b.Property<string>("ConnectorInstance")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connector_instance");

                    b.Property<string>("DataPoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_point");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_type");

                    b.Property<long>("FacilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("facility_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("TriggerType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trigger_type");

                    b.Property<string>("TriggerValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_value");

                    b.HasKey("Id");

                    b.ToTable("tsjy_alarm_definition", (string)null);
                });

            modelBuilder.Entity("Tsjy.Models.TsjyAlarmHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AlarmDefinitionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alarm_definition_id");

                    b.Property<long?>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration");

                    b.Property<long?>("EndTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("end_time");

                    b.Property<long>("FacilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("facility_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.ToTable("tsjy_alarm_history", (string)null);
                });

            modelBuilder.Entity("Tsjy.Models.TsjyCraftBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BindingType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("binding_type");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_name");

                    b.Property<string>("ConnectorInstance")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connector_instance");

                    b.Property<string>("DataPoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_point");

                    b.Property<long>("FacilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("facility_id");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER")
                        .HasColumnName("index");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tsjy_craft_binding", (string)null);
                });

            modelBuilder.Entity("Tsjy.Models.TsjyCraftData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BindingType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("binding_type");

                    b.Property<long>("FacilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("facility_id");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER")
                        .HasColumnName("index");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("tsjy_craft_data", (string)null);
                });

            modelBuilder.Entity("Tsjy.Models.TsjyMotor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("FacilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("facility_id");

                    b.Property<string>("LowerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("lower_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tsjy_motor", (string)null);
                });

            modelBuilder.Entity("Tsjy.Models.TsjyMotorBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BindingType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("binding_type");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_name");

                    b.Property<string>("ConnectorInstance")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connector_instance");

                    b.Property<string>("DataPoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_point");

                    b.Property<long>("MotorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("motor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tsjy_motor_binding", (string)null);
                });

            modelBuilder.Entity("Tsjy.Models.TsjyProductionBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BindingType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("binding_type");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_name");

                    b.Property<string>("ConnectorInstance")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connector_instance");

                    b.Property<string>("DataPoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_point");

                    b.Property<long>("FacilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("facility_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tsjy_production_binding", (string)null);
                });

            modelBuilder.Entity("Tsjy.Models.TsjyProductionData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CompleteTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("complete_time");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_code");

                    b.Property<long>("FacilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("facility_id");

                    b.Property<string>("MaterialSpecification")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("material_specification");

                    b.HasKey("Id");

                    b.ToTable("tsjy_production_data", (string)null);
                });

            modelBuilder.Entity("Tsjy.Models.TsjyStatusBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BindingType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("binding_type");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_name");

                    b.Property<string>("ConnectorInstance")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connector_instance");

                    b.Property<string>("DataPoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_point");

                    b.Property<long>("FacilityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("facility_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tsjy_status_binding", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
