// <auto-generated />
using Faoem.Variable.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Faoem.Variable.Migrations.Sqlite
{
    [DbContext(typeof(SqliteVariableDbContext))]
    [Migration("20240823072720_000002")]
    partial class _000002
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Faoem.Variable.Models.ArchivedVariable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArchiveInterval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archive_interval");

                    b.Property<int>("ArchiveMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archive_mode");

                    b.Property<int>("ArchiveType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("archive_type");

                    b.Property<string>("ConnectionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_name");

                    b.Property<string>("ConnectorInstance")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("connector_instance");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("DataPoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_point");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("variable_archived_variable", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
