export const variableArchiveLang = {
  en: {
    el: {
      variableArchive: {
        variableArchive: 'Variable Archive',
        connectorInstance: 'Connector Instance',
        connectionName: 'Connection Name',
        dataPointName: 'Data Point Name',
        name: 'Name',
        archiveType: 'Archive Type',
        archiveMode: 'Archive Mode',
        archiveInterval: 'Archive Interval',
        nameFilterPlaceholder: 'enter variable name',
        filter: 'Filter',
        addArchive: 'Add Archive',
        dataType: 'Data Type',
        add: 'Add',
        archivedVariableAddSuccessful: 'The variable has been archived.',
        archivedVariableAddFailed: 'Failed to archive the variable.',
        notApplicable: 'N/A',
        userArchiveType: 'User Archive',
        systemArchiveType: 'System Archive',
        archiveOnChanged: 'On Changed',
        archiveOnInterval: 'On Interval',
        updateArchive: 'Update Archive',
        update: 'Update',
        delete: 'Delete',
        archiveIntervalUnit: 'second(s)',
        archivedVariableUpdateSuccessful: 'The variable has been updated.',
        archivedVariableUpdateFailed: 'Failed to update the variable.',
        deleteArchiveVariable: 'Delete Archive Variable',
        archivedVariableDeleteSuccessful: 'The variable has been deleted.',
        archivedVariableDeleteFailed: 'Failed to delete the variable.',
        deleteArchiveConfirm:
          'This action cannot be undone. Are you sure you want to delete the archive variable?',
      },
    },
  },
  zhCn: {
    el: {
      variableArchive: {
        variableArchive: '变量归档',
        connectorInstance: '连接器实例',
        connectionName: '连接名称',
        dataPointName: '数据点名称',
        name: '名称',
        archiveType: '归档类型',
        archiveMode: '归档模式',
        archiveInterval: '归档间隔',
        filter: '筛选',
        nameFilterPlaceholder: '输入变量名称',
        addArchive: '添加归档',
        dataType: '数据类型',
        add: '添加',
        archivedVariableAddSuccessful: '变量已归档',
        archivedVariableAddFailed: '变量归档失败',
        notApplicable: '不适用',
        userArchiveType: '用户归档',
        systemArchiveType: '系统归档',
        archiveOnChanged: '变化时归档',
        archiveOnInterval: '周期归档',
        updateArchive: '更新归档',
        update: '更新',
        delete: '删除',
        archiveIntervalUnit: '秒',
        archivedVariableUpdateSuccessful: '归档变量已更新',
        archivedVariableUpdateFailed: '归档变量更新失败',
        deleteArchiveVariable: '删除归档变量',
        archivedVariableDeleteSuccessful: '归档变量已删除',
        archivedVariableDeleteFailed: '归档变量删除失败',
        deleteArchiveConfirm: '删除后无法恢复，确定要删除归档变量吗？',
      },
    },
  },
}
