export const testLang = {
  en: {
    el: {
      test: {
        mqttTest: 'Mqtt Test',
        connected: 'Connected',
        disconnected: 'Disconnected',
        clientId: 'Client ID: ',
        subscribe: 'Subscribe',
        unsubscribe: 'Unsubscribe',
        atMostOnce: '0 - At most once',
        atLeastOnce: '1 - At least once',
        exactlyOnce: '2 - Exactly once',
        subscribeTopic: 'Subscribe Topic',
        topic: 'Topic',
        topicColon: 'Topic: ',
        qos: 'QoS',
        subscribeSuccessful: 'Subscribe successful',
        subscribeFailed: 'Subscribe failed',
        unsubscribeSuccessful: 'Unsubscribe successful',
        unsubscribeFailed: 'Unsubscribe failed',
        retained: 'Retained',
        autoScroll: 'Auto Scroll',
      },
    },
  },
  zhCn: {
    el: {
      test: {
        mqttTest: 'Mqtt 测试',
        connected: '已连接',
        disconnected: '未连接',
        clientId: '客户端 ID: ',
        subscribe: '订阅',
        unsubscribe: '取消订阅',
        atMostOnce: '0 - 最多一次',
        atLeastOnce: '1 - 至少一次',
        exactlyOnce: '2 - 仅一次',
        subscribeTopic: '订阅主题',
        topic: '主题',
        topicColon: 'Topic: ',
        qos: 'QoS',
        subscribeSuccessful: '订阅成功',
        subscribeFailed: '订阅失败',
        unsubscribeSuccessful: '取消订阅成功',
        unsubscribeFailed: '取消订阅失败',
        retained: 'Retained',
        autoScroll: '自动滚动',
      },
    },
  },
}
