export const stoppedDataLang = {
  en: {
    el: {
      stoppedData: {
        stoppedData: 'Downtime Data',
        filter: 'Filter',
        statusCompare: 'Status Compare',
        shiftCompare: 'Shift Compare',
        historicalDowntime: 'Historical Downtime',
        statusRecord: 'Status Record',
        minutes: 'Minutes',
        running: 'Running',
        standby: 'Standby',
        stopped: 'Stopped',
        error: 'Error',
        shift: 'Shift',
        downtime: 'Downtime',
        date: 'Date',
        time: 'Time',
        status: 'Status',
        duration: 'Duration',
        invalid: 'Invalid',
        last7Days: 'Last 7 Days',
        last14Days: 'Last 14 Days',
        last30Days: 'Last 30 Days',
        moreThan1Day: '> 1 day',
      },
    },
  },
  zhCn: {
    el: {
      stoppedData: {
        stoppedData: '停机数据',
        filter: '筛选',
        statusCompare: '状态对比',
        shiftCompare: '班次停机时长对比',
        historicalDowntime: '历史停机时长',
        statusRecord: '状态记录',
        minutes: '分钟',
        running: '运行',
        standby: '待机',
        stopped: '停机',
        error: '故障',
        shift: '班次',
        downtime: '停机时长',
        date: '日期',
        time: '时间',
        status: '状态',
        duration: '持续时间',
        invalid: '无效',
        last7Days: '最近 7 天',
        last14Days: '最近 14 天',
        last30Days: '最近 30 天',
        moreThan1Day: '> 1 天',
      },
    },
  },
}
